apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  selector:
    matchLabels:
      app: inventory-db
  serviceName: inventory-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: inventory-db
        image: postgres:16
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: INVENTORY_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: INVENTORY_DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: INVENTORY_DB_NAME
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: INVENTORY_PG_DATA
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: www
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard-rwo"
      volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
spec:
  clusterIP: None
  selector:
    app: inventory-db
  ports:
  - port: 5432
    targetPort: 5432

