INSERT INTO products (title, stock, price) VALUES
                                              ('Smartphone', 50, 699.99),
                                              ('Laptop', 30, 1299.99),
                                              ('Tablet', 40, 499.99),
                                              ('Smartwatch', 60, 249.99),
                                              ('Wireless Earbuds', 100, 99.99),
                                              ('Bluetooth Speaker', 45, 149.99),
                                              ('Gaming Mouse', 80, 59.99),
                                              ('Mechanical Keyboard', 70, 89.99),
                                              ('Monitor', 35, 299.99),
                                              ('Printer', 25, 199.99),
                                              ('External Hard Drive', 55, 79.99),
                                              ('USB Flash Drive', 150, 19.99),
                                              ('Webcam', 50, 49.99),
                                              ('Router', 30, 129.99),
                                              ('Power Bank', 90, 39.99),
                                              ('Graphics Card', 20, 599.99),
                                              ('Processor', 25, 349.99),
                                              ('RAM 16GB', 75, 89.99),
                                              ('SSD 1TB', 65, 119.99),
                                              ('Laptop Stand', 85, 29.99);